dist: bionic
language: cpp

os:
  - linux

compiler:
  - clang
  - gcc

cache:
  directories:
    - $HOME/.cache

addons:
  apt:
    packages:
    - cmake

install:
  - ./scripts/install.sh

script:
  - ./scripts/compile.sh

notifications:
  email:
   - Cyanide.github@googlemail.com
