dist: bionic
language: cpp

os:
  - linux

compiler:
  - clang
  - gcc

cache:
  directories:
    - $HOME/.cache

addons:
  apt:
    packages:
    - python3-pip
    - cmake

before_install:
  - chmod +x ./scripts/install.sh

install:
  - ./scripts/install.sh

before_script:
  - chmod +x ./scripts/compile.sh

script:
  - ./scripts/compile.sh

notifications:
  email:
   - Cyanide.github@googlemail.com
