language: cpp

os:
  - linux

compiler:
  - clang
  - gcc

cache:
  directories:
    - $HOME/.cache

addons:
  apt:
    packages:
    - clang-6.0
    - gcc-7
    - cmake

before_install:
  - mkdir build
  - sudo apt-get update
  - sudo apt-get install -y libsdl2-2.0.0
  - sudo apt-get install -y libsdl2-dev
  - sudo apt-get install -y libsdl2-gfx-1.0.0
  - sudo apt-get install -y libsdl2-gfx-dev
  - sudo apt-get install -y libsdl2-image-2.0.0
  - sudo apt-get install -y libsdl2-image-dev
  - sudo apt-get install -y libsdl2-mixer-2.0.0
  - sudo apt-get install -y libsdl2-mixer-dev
  - sudo apt-get install -y libsdl2-net-2.0.0
  - sudo apt-get install -y libsdl2-net-dev
  - sudo apt-get install -y libsdl2-ttf-2.0.0
  - sudo apt-get install -y libsdl2-ttf-dev

install:
  - sudo python -m pip install conan

script:
  - conan install . -if build
  - cd build
  - cmake .. && make
  - cd ..

notifications:
  email:
   - Cyanide.github@googlemail.com