language: cpp

#env:
#  global:
#    - RUN_TESTS=true
#    - COVERAGE=false

os:
  - linux
#  - windows

compiler:
  - clang
  - gcc

cache:
  directories:
    - $HOME/.cache

addons:
  apt:
    sources:
#    - ubuntu-toolchain-r-test
#    - llvm-toolchain-precise-3.8
    - libsdl2-2.0.0
    - libsdl2-dev
    - libsdl2-gfx-1.0.0
    - libsdl2-gfx-dev
    - libsdl2-image-2.0.0
    - libsdl2-image-dev
    - libsdl2-mixer-2.0.0
    - libsdl2-mixer-dev
    - libsdl2-net-2.0.0
    - libsdl2-net-dev
    - libsdl2-ttf-2.0.0
    - libsdl2-ttf-dev

    packages:
    - python3-pip
#    - clang-6.0
#    - gcc-7

    - cmake

#    - lcov

#before_install:
#  - eval "${MATRIX_EVAL}"

install:
  - sudo pip3 install --upgrade pip
  - sudo pip3 install conan
#  - "[ $CXX = clang++ ] && export CXX=clang++-3.8 || true"
#  - "[ $CXX = g++ ] && export CXX=g++-6 || true"

script:
  - conan install . build/
  - cmake .
#  - sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
#  - sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++

#after_success:
#  - lcov --capture --directory . --output-file coverage.info
#  - lcov --remove coverage.info '/usr/*' --output-file coverage.info
#  - lcov --list coverage.info
#  - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"

#notifications:
#  email:
#   - Cyanide@gmail.com