name: C/C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: install
      run: ./scripts/install.sh
    - name: compile
      run: ./scripts/compile.sh
